export interface TableModel {
  "meta": {
    "size": number,
    "limit": number,
    "offset": number
  },
  "passes": Array<Pass>,
}

export interface Pass {
  "user_id": number,
  "template": string | null,
  "fio": string | null,
  "first_name": string | null,
  "last_name": string | null
  "pat_name": string | null,
  "phone": string | null,
  "sms_verify": boolean | null,
  "email": string | null,
  "birthday": string | null,
  "gender": string | null,
  "car_number": string | null,
  "discount": string | null,
  "bonus": string | null,
  "bonus_last": string | null,
  "write_off_last": string | null,
  "loyalty_level": string | null,
  "summ": string | null,
  "summ_all": string | null,
  "summ_last": string | null,
  "visits": string | null,
  "visits_all": string | null,
  "date_last": string | null,
  "barcode": string | null,
  "key1": string | null,
  "key2": string | null,
  "key3": string | null,
  "key4": string | null,
  "key5": string | null,
  "key6": string | null,
  "trg_action_type": string | null,
  "trg_action_value": string | null,
  "trg_date_type": string | null,
  "trg_date_value": string | null,
  "delivery_form": string,
  "o_s": string,
  "link": string | null,
  "referal": string | null,
  "backgroundColor": string | null,
  "created_at": string | null,
  "H1": string | null,
  "H2": string | null,
  "H3": string | null,
  "S1": string | null,
  "S2": string | null,
  "S3": string | null,
  "B1": string | null,
  "B2": string | null,
  "B3": string | null,
  "B4": string | null,
  "B5": string | null,
  "B6": string | null,
}
